apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: techyz-hpa
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: techyz-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50